# Application Context Path
server:
  servlet:
    context-path: /helpdesk
<<<<<<< HEAD

# Spring Configuration
=======
# Swagger-ui
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
# Application Name
>>>>>>> 7ba51ed (swagger-ui updated)
spring:
  application:
    name: help-desk-backend
#Active Profile
  profiles:
    active: dev
# JPA
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
#Ollama model configure
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3.2:latest
          temperature: 0.7
#Chat memory configure
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
# OAuth2 Google & GitHub configure
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - email
              - profile
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope:
              - read:user
              - user:email
# Swagger Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
    try-it-out-enabled: true
# Logging
logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG
# Custom Properties
another:
  student: true
# AI Memory
ai:
  memory:
    max-messages: 20
# JWT
jwt:
  secret-key: ${JWT_SECRET}
  expiration: 86400000